services:
  - type: web
    name: ai-recipe-recommender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run gui.py --server.address 0.0.0.0 --server.port $PORT --server.headless true --server.baseUrlPath ""
    envVars:
      - key: SPOONACULAR_API_KEY
        sync: false
